a=int (input("enter number 1:"))
b=int (input("enter number 2:"))
print("sum of 2 numbers is:",a+b)
print("difference of 2 numbers is:",a-b)
print("product of 2 numbers is:",a*b)
print("quotient of 2 numbers is:",a/b)
print("the result of floor division is",a//b)
print("remainder of 2 numbers is:",a%b)
print("cube of first number is:",a**3)
print("cube of second number is:",b**3)